News/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from .views import (PostsList,
                    PostDetail,
                    PostsSearch,
                    NewsCreate,
                    ArticleCreate,
                    NewsUpdate,
                    ArticleUpdate,
                    NewsDelete,
                    ArticleDelete
                    )


urlpatterns = [
    path('', PostsList.as_view(), name='post_list'),
    path('<int:pk>', PostDetail.as_view(), name='post_detail'),
    path('search/', PostsSearch.as_view(), name='post_search'),
    path('create/', cache_page(60*10)(NewsCreate.as_view()), name='news_create'),
    path('<int:pk>/edit/', NewsUpdate.as_view(), name='news_edit'),
    path('<int:pk>/delete/', NewsDelete.as_view(), name='news_delete'),
    path('articles/create/', cache_page(60*10)(ArticleCreate.as_view()), name='articles_create'),
    path('articles/<int:pk>/edit/', ArticleUpdate.as_view(), name='articles_edit'),
    path('articles/<int:pk>/delete/', ArticleDelete.as_view(), name='articles_delete'),
]

NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include

from News.views import subscriptions

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    # Делаем так, чтобы все адреса из нашего приложения (simpleapp/urls.py)
    # подключались к главному приложению с префиксом products/.
    path('news/', include('News.urls')),
    path("accounts/", include("allauth.urls")),
    path('subscriptions/', subscriptions, name='subscriptions'),
]

News/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.core.cache import cache

import News.resourses as rs
from django.db.models import Sum


class Author(models.Model):
    author = models.OneToOneField(User, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)

    def update_rating(self):
        rate = 0
        r1 = self.posts.aggregate(postRating=Sum('rating'))
        rate += r1.get('postRating') * 3
        r2 = self.author.comments.aggregate(commentRating=Sum('rating'))
        rate += r2.get('commentRating')
        for i in self.posts.all():
            r3 = i.comments_set.aggregate(postcommentRating=Sum('rating'))
            rate += r3.get('postcommentRating')
        # #суммарный рейтинг каждой статьи автора умножается на 3
        # if Post.objects.filter(author_id=self.pk).exists():
        #     r1 = Post.objects.filter(author_id=self.pk).values('rating', 'pk')
        #     rate += sum([r1[i]['rating'] for i in range(len(r1))]) * 3
        #     #суммарный рейтинг всех комментариев к статьям автора
        #     post_pk = [r1[i]['pk'] for i in range(len(r1))]
        #     for i in post_pk:
        #         r3 = Comments.objects.filter(post_id=i).values('rating')
        #         rate += sum([r3[i]['rating'] for i in range(len(r3))])
        # #суммарный рейтинг всех комментариев автора
        # if Comments.objects.filter(author_id=self.author).exists():
        #     r2 = Comments.objects.filter(author_id=self.author).values('rating')
        #     rate += sum([r2[i]['rating'] for i in range(len(r2))])
        self.rating = rate
        self.save()

    def __str__(self):
        return f'{self.author}'


class Category(models.Model):
    category = models.CharField(max_length=60, unique=True)

    def __str__(self):
        return f'{self.category}'


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name='posts')
    type = models.CharField(max_length=1, choices=rs.TYPES, default=rs.news_type)
    time_creation = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    post = models.TextField()
    rating = models.IntegerField(default=0)
    category = models.ManyToManyField(Category, through='PostCategory')

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.pk)])

    def preview(self):
        return f"{self.post[:124:]}..."

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def __str__(self):
        return f'{self.title}: {self.author}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        cache.delete(f'post-{self.pk}')


class PostCategory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)


class Comments(models.Model):
    comment = models.TextField()
    time_creation = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()


class Subscription(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )

templates/post_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
{% load cache %} <!-- Загружаем кэширование -->
    {% cache 30 post_delete %}
<h1>Post delete</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Delete "{{ object.title }} ({{ object.author }})"?</p>
    <input type="submit" value="Delete" />
</form>
    {% endcache %}
{% endblock content %}

templates/post_details.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
{% load mytags %}


{% block title %}
Post details
{% endblock title %}


{% block content %}
<h1><strong>{{ post_details.title|censor }}</strong></h1>
<br>
<h4 align="left"><em>{{ post_details.time_creation|date:'d.m.Y' }} - by {{ post_details.author }}</em></h4>
<hr>
<p>{{ post_details.post|censor }}</p>
<hr>

<table>
{% for cmnts in post_details.comments_set.all %}
    <tr>
        <td>{{cmnts.author}} comment:</td>
        <td align="left">{{cmnts.comment}}</td>
    </tr>
{% endfor %}
</table>

{% if post_details.type == 'A' %}
    <table>
        <tr>
            <td>
                {% if perms.News.change_post %}
                <form action="articles/{{ post_details.pk }}/edit/" >
                    <input type="submit" value="Edit" />
                </form>
                {% endif %}
            </td>
            <td>
                {% if perms.News.delete_post %}
                <form action="articles/{{ post_details.pk }}/delete/" >
                    <input type="submit" value="Delete" />
                </form>
                {% endif %}
            </td>
        </tr>
    </table>

{% else %}
    <table>
        <tr>
            <td>
                {% if perms.News.change_post %}
                <form action="{{ post_details.pk }}/edit/" >
                    <input type="submit" value="Edit" />
                </form>
                {% endif %}
            </td>
            <td>
                {% if perms.News.delete_post %}
                <form action="{{ post_details.pk }}/delete/" >
                    <input type="submit" value="Delete" />
                </form>
                {% endif %}
            </td>
        </tr>
    </table>
{% endif %}

{% endblock content %}

templates/post_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>{{ type }}</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

templates/posts.html
{% extends 'flatpages/default.html' %}
{% load mytags %}
{% load custom_filters %}
<!-- Название у нас будет products -->
{% block title %}
Posts: news & articles
{% endblock title %}


{% block content %}
{% if posts %}
<h1>{{posts|length}} POSTS:</h1>
    <table>
        {% for post in posts %}
        <tr>
            <td colspan="2" align="left"> <em>
            {% for cat in post.category.all %}
                {{cat}}
            {% endfor %}
            </em></td>
        </tr>
        <tr>
            <td align="left"> <strong> {{ post.time_creation|date:'d.m.Y' }} </strong></td>
            <td align="left"><a href={% hrefcreate value=post.pk %}> {{ post.title|censor }} </a></td>
        </tr>
        <tr>
            <td colspan="2" align="left"> <em> {{ post.post|truncatechars:20 }} </em></td>
        </tr>
        {% endfor %}
    </table>
{% else %}
<h2>Статей и новостей нет!</h2>
{% endif %}

 {# Добавляем пагинацию на страницу #}

   {# Информация о предыдущих страницах #}
   {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}
<hr>
{# Теперь будем проверять не request.user.is_authenticated, а конкретные права #}
{% if perms.News.add_post %}
<table>
    <tr>
        <td>
            <form action="{% url 'news_create' %}" >
                <input type="submit" value="News posting" />
            </form>
        </td>
        <td>
            <form action="{% url 'articles_create' %}" >
                <input type="submit" value="Articles posting" />
            </form>
        </td>
    </tr>
</table>
{% endif %}

{% endblock content %}>

templates/search.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}
{% load mytags %}
{% load custom_filters %}
<!-- Название у нас будет Product -->
{% block title %}
Post details
{% endblock title %}

<!-- В контенте на странице мы выводим сам товар, идентификатор которого был передан в url -->
{% block content %}
<form action="" method="get">
    {{ filterset.form.as_p }}
    <input type="submit" value="Найти" />
</form>

{% if posts_search %}
<h1>{{posts_search|length}} POSTS:</h1>
    <table>
        {% for post in posts_search %}
        <tr>
            <td colspan="2" align="left"> <em>
            {% for cat in post.category.all %}
                {{cat}}
            {% endfor %}:
            </em></td>
        </tr>
        <tr>
            <td align="left"> <strong> {{ post.time_creation|date:'d.m.Y' }} </strong></td>
            <td align="left"><a href={%  hrefcreate value=post.pk %}> {{ post.title|censor }} </a></td>
        </tr>
        <tr>
            <td colspan="2" align="left"> <em> {{ post.post|truncatechars:20 }} </em></td>
        </tr>
        {% endfor %}
    </table>
{% else %}
<h2>Статей и новостей нет!</h2>
{% endif %}

{# Добавляем пагинацию на страницу #}

   {# Информация о предыдущих страницах #}
   {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}
<hr>
{% endblock content %}

templates/subscriptions.html
{% extends 'flatpages/default.html' %}

{% block title %}
Subscriptions
{% endblock title %}

{% block content %}
    {% for category in categories  %}
        <p>
            <strong>{{ category.category|upper }}</strong>
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="category_id" value="{{ category.id }}" />

                {% if category.user_subscribed %}
                    <button disabled>Subscribe</button>
                    <button name="action" value="unsubscribe">Unsubscribe</button>
                {% else %}
                    <button name="action" value="subscribe">Subscribe</button>
                    <button disabled>Unsubscribe</button>
                {% endif %}
            </form>
        </p>
    {% endfor %}
{% endblock content %}

templates/weekly_posts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Weekly posts</title>
</head>
<body>
<h1>Weekly posts in {{ category }} category:</h1>
<ul>
    {% for post in posts %}
    <li>
        <a href="{{ link }}{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>
</body>
</html>